### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by brow** [mrzealot/absolem#1]
I encounter this error when I [set my `glue`'s `top.right.rotate` equal to `points.rotate` and `top.left.rotate` equal to the negation of that](https://github.com/mrzealot/ergogen/commit/8f416d7e0d1e39a4b832cebc0ddcd024d460fb38).

``` bash
> git rev-parse HEAD
8f416d7e0d1e39a4b832cebc0ddcd024d460fb38
> node src/cli.js -c jklp.yaml -o jklp --debug
Parsing points...
Generating outlines...
/Users/tombrow/Documents/ergogen/src/utils.js:6
    return a[0] === b[0] && a[1] === b[1]
                     ^

TypeError: Cannot read property '0' of null
    at Object.exports.eq (/Users/tombrow/Documents/ergogen/src/utils.js:6:22)
    at /Users/tombrow/Documents/ergogen/src/outlines.js:155:27
    at Object.exports.parse (/Users/tombrow/Documents/ergogen/src/outlines.js:238:27)
    at Object.<anonymous> (/Users/tombrow/Documents/ergogen/src/cli.js:79:31)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
```

The error does not occur if `top.right.rotate` differs from `points.rotate` or from negative `top.left.rotate`.

**Comment by brow** [comment]
Oops, this issue was meant for Ergogen! https://github.com/mrzealot/ergogen/issues/8
